# Generated by Django 3.0.4 on 2020-03-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_income2_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income2',
        ),
    ]
